### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by mercury233**

### CODE REVIEW

**Comment by ahtelel** [comment]
I believe some of the fixes in this commit PR are already in some of the opened PRs

**Comment by mercury233** [comment]
sorry i didn't noticed it

**Comment by ahtelel** [comment]
Would you like to open another PR with the fixes that we don't already have? I can do it in your stead if you want

**Comment by mercury233** [comment]
@ahtelel done

**Comment by ahtelel** [comment]
@edo9300 Mergeable now

**Pull request merged**
