### PR TITLE
Fixed "Iron Draw"

### PR DESCRIPTION
**Pull request by NaimSantos**
Fixed a bug where you could still activate it while you control other monsters besides the 2 machine effect monster

### CODE REVIEW

**Comment by mercury233** [comment]
_If you control exactly 2 Machine Effect Monsters_
https://yugipedia.com/wiki/Iron_Draw
this pr will enable it with only 1 machine and 1 other monster

**Comment by mercury233** [comment]
btw, if this effect is used by Diamond Dude, the limit shouldn't apply

**Comment by EerieCode** [comment]
How about `return Duel.GetFieldGroupCount(tp,LOCATION_MZONE,0)==2 and Duel.GetMatchingGroupCount(c100227034.cfilter,tp,LOCATION_MZONE,0,nil)==2`?

**Comment by mercury233** [comment]
[my way](https://github.com/Fluorohydride/ygopro-pre-script/blob/master/scripts/CP18-JP/c100227034.lua#L18)

**Comment by EerieCode** [comment]
Thanks! I've uploaded a patch [here](https://github.com/Ygoproco/Live2017Links/commit/7a265230c67384067703ea43c2e7c6fcc090f425), so I'll close the request.

**Pull request closed without merging**
