### PR TITLE
Fixed WIld-Fire

### PR DESCRIPTION
**Pull request by TheOnePharaoh**
Effect should destroy only 1 "Blaze Accelerator" card not all of them

### CODE REVIEW

**Comment by NaimSantos** [comment]
Closed, because that's the [correct behaviour](http://yugioh-wiki.net/index.php?%A1%D4%A5%AF%A5%EC%A5%A4%A5%B8%A1%BC%A1%A6%A5%D5%A5%A1%A5%A4%A5%E4%A1%BC%A1%D5)

**Comment by TheOnePharaoh** [comment]
@NaimSantos 
`Destroy a face-up "Blaze Accelerator" card you control `
it needs to destroy 1 card not all "Blaze Accelerator" cards
`It can also be activated when Blaze Cannon, which has been treated as a monster by Magical Top Hat , is face-up in the monster zone .`
from the page you posted

**Comment by AlphaKretin** [comment]
Naim cited an OCG ruling from a trusted source, which outranks English card text, especially being as old as it is (far far before the instution of PSCT).
> Ｑ：「 ブレイズ・キャノン 」と名のつくカードが複数存在する場合はどうなりますか？
> Ａ：すべて破壊します。

> Q: What happens if there are multiple cards named “ Blaze Cannon ”?
> A: All will be destroyed .

**Comment by TheOnePharaoh** [comment]
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=7089&request_locale=ja
this is the official OCG ruling page 
image

**Comment by AlphaKretin** [comment]
Japanese doesn't have a distinction between singular and plural and it's inaccurate of google translate to insert one. It's safe to assume (and consistent with other card text) that if they meant exactly 1, they would specify "1".

**Comment by TheOnePharaoh** [comment]
https://github.com/Ygoproco/Live2017Links/pull/2301
I updated only the confirmed parts from the OCG ruling for now and I will get confirmation regarding the rest from the OCG office later on

**Pull request closed without merging**
