### PR TITLE
fix for Borrel Regenerator, boresword and link turret.

### PR DESCRIPTION
**Pull request by AndreOliveiraMendes**
typo in function name.

### CODE REVIEW

**Comment by Sun4Ever2** [comment]
borrelsword boost effects are not working just saying.

**Comment by AndreOliveiraMendes** [comment]
@Sun4Ever2 what do you mean by it?

**Comment by Sun4Ever2** [comment]
I mean I change my oponent monster position and then I attack it with boreelsword but nothing happends he doesnt gain the boost attack that he suposed to had

**Comment by AndreOliveiraMendes** [comment]
do you have debug mode on?
wich error apear?

**Pull request merged**
