### PR TITLE
Update for "Noble Knight Custennin"

### PR DESCRIPTION
**Pull request by NaimSantos**

### CODE REVIEW

**Comment by NaimSantos** [comment]
As [mentioned here](https://ygorganization.com/whenyoureupat12amathomeandyouforgettofeedmerlin/), the japanese text allow any extra normal summon.

**Comment by EerieCode** [comment]
Has this confirmed to be the actual effect, or is it a misprint in the physical cards? I think we should wait for the official database before merging, just to be sure

**Comment by NaimSantos** [comment]
I'm fine with that. I also changed the type of activation, a detail missed in the previous commit.

**Comment by NaimSantos** [comment]
The change is, indeed, what was mentioned, as can be seen [in the database](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=13984&request_locale=ja)

**Pull request merged**
